app:
  name: pivot
  buildpack: nixpacks
  domains:
    - pivot.guillaume-lcte.fr
  port: 4004
  env:
    APP_NAME: Pivot
    APP_ENV: production
    APP_KEY: base64:gmBDzoUYk3CFz7M2ePt3hC+wUyIPvggqmyOd9EZRL94=
    APP_DEBUG: false
    APP_URL: https://pivot.guillaume-lcte.fr
    ASSET_URL: https://pivot.guillaume-lcte.fr
    FORCE_HTTPS: true

    LOG_CHANNEL: stack
    LOG_DEPRECATIONS_CHANNEL: null
    LOG_LEVEL: error

    DB_CONNECTION: mysql
    DB_HOST: 51.195.43.106
    DB_PORT: 3306
    DB_DATABASE: pivot
    DB_USERNAME: pivot
    DB_PASSWORD: pivot

    BROADCAST_DRIVER: log
    CACHE_DRIVER: file
    FILESYSTEM_DISK: local
    QUEUE_CONNECTION: sync

    SESSION_DRIVER: file
    SESSION_LIFETIME: 120
    SESSION_SECURE_COOKIE: true
    SESSION_SAME_SITE: lax
    SESSION_DOMAIN: .guillaume-lcte.fr
    SESSION_ENCRYPT: false
    SESSION_PATH: /

    CACHE_STORE: file

    REDIS_HOST: 127.0.0.1
    REDIS_PASSWORD: null
    REDIS_PORT: 6379

    MAIL_MAILER: smtp
    MAIL_HOST: 51.195.43.106
    MAIL_PORT: 1025
    MAIL_USERNAME: null
    MAIL_PASSWORD: null
    MAIL_ENCRYPTION: null
    MAIL_FROM_ADDRESS: noreply@guillaume-lcte.fr
    MAIL_FROM_NAME: "${APP_NAME}"

    VITE_APP_NAME: "${APP_NAME}"
    VITE_APP_URL: "${APP_URL}"

  # Configuration d'intégration continue
  source:
    type: git
    repository: https://github.com/votre-username/pivot.git
    branch: main
    
  # Healthcheck pour s'assurer que l'app fonctionne
  healthcheck:
    test: ["CMD", "curl", "-f", "http://localhost:4004/health"]
    interval: 30s
    timeout: 10s
    retries: 3
    start_period: 40s

  labels:
    - "traefik.enable=true"
    - "traefik.http.routers.pivot-awlyhs.entrypoints=websecure"
    - "traefik.http.routers.pivot-awlyhs.rule=Host(`pivot.guillaume-lcte.fr`)"
    - "traefik.http.routers.pivot-awlyhs.tls=true"
    - "traefik.http.services.pivot-awlyhs.loadbalancer.server.port=4004"
    - "traefik.http.services.pivot-awlyhs.loadbalancer.server.scheme=http"
    - "traefik.http.middlewares.redirect-https.redirectscheme.scheme=https"
    - "traefik.http.middlewares.redirect-https.redirectscheme.permanent=true"
    - "traefik.http.routers.pivot-awlyhs.middlewares=redirect-https"
    - "traefik.docker.network=dokploy-network"

services:
  mysql:
    image: mysql:8.0
    env:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: pivot
      MYSQL_USER: pivot
      MYSQL_PASSWORD: pivot
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:alpine
    volumes:
      - redis_data:/data

  mailpit:
    image: axllent/mailpit
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  mysql_data:
  redis_data: 