[phases.setup]
nixPkgs = ["nodejs", "php", "composer"]

[phases.install]
cmds = [
    "composer install --no-dev --optimize-autoloader",
    "npm install",
    "npm run build"
]

[phases.build]
cmds = [
    "php artisan config:cache",
    "php artisan route:cache",
    "php artisan view:cache"
]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=4004"

[variables]
APP_NAME = "Pivot"
APP_ENV = "production"
APP_KEY = "base64:gmBDzoUYk3CFz7M2ePt3hC+wUyIPvggqmyOd9EZRL94="
APP_DEBUG = "false"
APP_URL = "https://pivot.guillaume-lcte.fr"
ASSET_URL = "https://pivot.guillaume-lcte.fr"
FORCE_HTTPS = "true"

LOG_CHANNEL = "stack"
LOG_DEPRECATIONS_CHANNEL = "null"
LOG_LEVEL = "error"

DB_CONNECTION = "mysql"
DB_HOST = "51.195.43.106"
DB_PORT = "3306"
DB_DATABASE = "pivot"
DB_USERNAME = "pivot"
DB_PASSWORD = "pivot"

BROADCAST_DRIVER = "log"
CACHE_DRIVER = "file"
FILESYSTEM_DISK = "local"
QUEUE_CONNECTION = "sync"

SESSION_DRIVER = "file"
SESSION_LIFETIME = "120"
SESSION_SECURE_COOKIE = "true"
SESSION_SAME_SITE = "lax"
SESSION_DOMAIN = ".guillaume-lcte.fr"
SESSION_ENCRYPT = "false"
SESSION_PATH = "/"

CACHE_STORE = "file"

REDIS_HOST = "127.0.0.1"
REDIS_PASSWORD = "null"
REDIS_PORT = "6379"

MAIL_MAILER = "smtp"
MAIL_HOST = "mailpit"
MAIL_PORT = "1025"
MAIL_USERNAME = "null"
MAIL_PASSWORD = "null"
MAIL_ENCRYPTION = "null"
MAIL_FROM_ADDRESS = "hello@example.com"
MAIL_FROM_NAME = "${APP_NAME}"

VITE_APP_NAME = "${APP_NAME}"
VITE_APP_URL = "${APP_URL}"
VITE_PUSHER_APP_KEY = "${PUSHER_APP_KEY}"
VITE_PUSHER_HOST = "${PUSHER_HOST}"
VITE_PUSHER_PORT = "${PUSHER_PORT}"
VITE_PUSHER_SCHEME = "${PUSHER_SCHEME}"
VITE_PUSHER_APP_CLUSTER = "${PUSHER_APP_CLUSTER}" 